# Generated by Django 2.2.5 on 2019-09-19 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExifType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('exif_id', models.IntegerField(blank=True, default=-1)),
                ('short', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.CharField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='MetaLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.FilePathField(max_length=1024, path='/home/chiara/foto/full', recursive=True)),
                ('thumb_path', models.FilePathField(max_length=1024, path='/home/chiara/foto/thumb', recursive=True)),
                ('description', models.CharField(blank=True, max_length=8192)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('mode', models.CharField(max_length=1024)),
                ('mimetype', models.CharField(max_length=1024)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('rotated', models.CharField(choices=[('no', 'no'), ('90 ccw', '90 ccw'), ('90 cw', '90 cw'), ('180', '180')], default='no', max_length=128)),
                ('mirrored', models.CharField(choices=[('no', 'no'), ('horizontal', 'horizontal'), ('vertical', 'vertical')], default='no', max_length=128)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.ImageFormat')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='PhotoMetaDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8192)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.MetaLabel')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='ExifLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('exif_id', models.IntegerField(blank=True, default=-1)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.ExifType')),
            ],
        ),
        migrations.CreateModel(
            name='ExifDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8192)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.ExifLabel')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('photos', models.ManyToManyField(blank=True, to='archive.Photo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
