# Generated by Django 3.0.2 on 2020-02-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='full_path',
            field=models.FilePathField(max_length=1024, path='/srv/archive/photo/full', recursive=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb_path',
            field=models.FilePathField(max_length=1024, path='/srv/archive/photo/thumb', recursive=True),
        ),
    ]
