# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='type',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
