# Generated by Django 3.0 on 2020-12-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20200222_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.FilePathField(max_length=1024, path='/srv/archive/document/full', recursive=True)),
                ('thumb_path', models.FilePathField(max_length=1024, path='/srv/archive/document/thumb', recursive=True)),
                ('mimetype', models.CharField(max_length=1024)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Document')),
            ],
            options={
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMetaDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8192)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Document')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.MetaLabel')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('documents', models.ManyToManyField(blank=True, to='archive.Document')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAssetMetaDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8192)),
                ('document_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.DocumentAsset')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.MetaLabel')),
            ],
        ),
    ]
