# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_photo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.CharField(max_length=8192)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='mode',
            field=models.CharField(default='RGB', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archive.ImageFormat'),
            preserve_default=False,
        ),
    ]
