# Generated by Django 3.0 on 2020-12-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_documentasset_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='label',
            field=models.SlugField(default='a'),
        ),
    ]
