# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_exiflabel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exiflabel',
            name='type',
            field=models.CharField(choices=[('tag', 'tag'), ('gps', 'gps'), ('undefined', 'undefined')], max_length=128),
        ),
    ]
