# Generated by Django 3.0 on 2020-12-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20201215_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=8192)),
            ],
        ),
    ]
