# Generated by Django 3.0 on 2020-12-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photod',
            name='label',
            field=models.SlugField(default='x', max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
