# Generated by Django 3.0 on 2020-12-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_photod_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='photod',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archive.Photo'),
        ),
    ]
