# Generated by Django 3.0 on 2020-12-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_photod_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
