# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_exiftype_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='exiflabel',
            name='exif_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='exiftype',
            name='exif_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
