# Generated by Django 3.0 on 2020-12-28 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_remove_photo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photod',
            options={'ordering': ['cover']},
        ),
        migrations.AddField(
            model_name='photod',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
