# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_auto_20170516_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='orientation',
            field=models.CharField(choices=[('normal', 'normal'), ('90 ccw', '90 ccw'), ('90 cw', '90 cw'), ('180', '180')], default='normal', max_length=128),
        ),
    ]
