# Generated by Django 3.0 on 2020-12-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_auto_20201228_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['photo']},
        ),
        migrations.AlterModelOptions(
            name='photod',
            options={'ordering': ['datetime']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='datetime',
        ),
    ]
