# Generated by Django 3.0 on 2020-12-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20201228_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='dphotos',
            field=models.ManyToManyField(blank=True, to='archive.PhotoD'),
        ),
    ]
