# Generated by Django 3.0 on 2020-12-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_album_dphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
    ]
