# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_photo_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
