# Generated by Django 3.0 on 2020-12-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_remove_album_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='dphotos',
            new_name='photos',
        ),
    ]
