# Generated by Django 3.0 on 2020-12-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_auto_20201228_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exifdatum',
            name='photod',
        ),
    ]
