# Generated by Django 3.0 on 2020-12-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_remove_exifdatum_photod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photometadatum',
            name='photo',
        ),
    ]
