# Generated by Django 3.0 on 2020-12-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_remove_photometadatum_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoAsset',
        ),
    ]
