# Generated by Django 3.0 on 2020-12-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_auto_20201228_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exifdatum',
            old_name='photo',
            new_name='asset',
        ),
    ]
