# Generated by Django 3.0 on 2020-12-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_auto_20201228_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photometadatum',
            old_name='photod',
            new_name='photo',
        ),
    ]
