# Generated by Django 3.0 on 2020-12-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_auto_20201228_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photod',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_cover', to='archive.PhotoAsset'),
        ),
    ]
