# Generated by Django 3.0 on 2020-12-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_auto_20201228_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoD',
            new_name='Photo',
        ),
    ]
