# Generated by Django 3.0 on 2020-12-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_auto_20201228_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAssetMetaDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8192)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.PhotoAsset')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.MetaLabel')),
            ],
        ),
    ]
