# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 15:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.Food')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('base', models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=128)),
                ('factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('serving', models.PositiveIntegerField(blank=True, default=4, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='StepSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipebook.StepSequence')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='step',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.StepSequence'),
        ),
        migrations.AddField(
            model_name='step',
            name='tools',
            field=models.ManyToManyField(to='recipebook.Tool'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.StepSequence'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.MeasureUnit'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='preparation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.StepSequence'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.Recipe'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebook.FoodCategory'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='stepsequence',
            order_with_respect_to='parent',
        ),
        migrations.AlterOrderWithRespectTo(
            name='step',
            order_with_respect_to='sequence',
        ),
    ]
