# Generated by Django 3.0.2 on 2020-02-21 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionToolRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('plural', models.CharField(blank=True, max_length=4096, null=True)),
                ('gender', models.CharField(choices=[('masculine', 'masculine'), ('neuter', 'neuter'), ('feminine', 'feminine')], default='masculine', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('inlist', models.BooleanField(blank=True, default=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Food')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientToolRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_new', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('base', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('qb', 'qb')], default='g', max_length=128)),
                ('factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('plural', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'order_with_respect_to': 'name',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=8192)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.StepSequence')),
                ('tools', models.ManyToManyField(blank=True, to='recipebook.Tool')),
            ],
            options={
                'order_with_respect_to': 'sequence',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('serving', models.PositiveIntegerField(blank=True, default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.RecipeCategory')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.StepSequence')),
                ('execution_tools', models.ManyToManyField(blank=True, related_name='recipe_execution_set', through='recipebook.ExecutionToolRelation', to='recipebook.Tool')),
                ('ingredient_tools', models.ManyToManyField(blank=True, related_name='recipe_ingredient_set', through='recipebook.IngredientToolRelation', to='recipebook.Tool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingredienttoolrelation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredienttoolrelation',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Step'),
        ),
        migrations.AddField(
            model_name='ingredienttoolrelation',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Tool'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipebook.MeasureUnit'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipebook.StepSequence'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.FoodCategory'),
        ),
        migrations.AddField(
            model_name='executiontoolrelation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe'),
        ),
        migrations.AddField(
            model_name='executiontoolrelation',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Step'),
        ),
        migrations.AddField(
            model_name='executiontoolrelation',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Tool'),
        ),
    ]
