# Generated by Django 3.0.2 on 2020-02-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepsequence',
            name='parent',
        ),
        migrations.CreateModel(
            name='IngredientToolRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_new', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Step')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionToolRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_new', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Step')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Tool')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='execution_tools',
            field=models.ManyToManyField(blank=True, related_name='recipe_execution_set', through='recipebook.ExecutionToolRelation', to='recipebook.Tool'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_tools',
            field=models.ManyToManyField(blank=True, related_name='recipe_ingredient_set', through='recipebook.IngredientToolRelation', to='recipebook.Tool'),
        ),
    ]
