# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0002_auto_20180317_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='plural',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
