# Generated by Django 3.0.2 on 2020-03-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0003_auto_20200315_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executiontoolrelation',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='ingredienttoolrelation',
            name='recipe',
        ),
    ]
