# Generated by Django 3.0.2 on 2020-03-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0005_auto_20200315_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientToolRelation',
        ),
    ]
