# Generated by Django 3.0.2 on 2020-03-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0006_delete_ingredienttoolrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='step',
            name='tools',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Food')),
                ('retailers', models.ManyToManyField(blank=True, to='recipebook.Retailer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
