# Generated by Django 3.0.2 on 2020-03-15 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0008_auto_20200315_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('ingredients', models.ManyToManyField(blank=True, to='recipebook.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredientGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.IngredientGroup')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredientAlternativeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.IngredientAlternative')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAlternativeGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.IngredientAlternative')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.IngredientGroup')),
            ],
        ),
    ]
