# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0008_food_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='gender',
            field=models.CharField(choices=[('masculine', 'masculine'), ('neuter', 'neuter'), ('feminine', 'feminine')], default='masculine', max_length=128),
        ),
    ]
