# Generated by Django 3.0.2 on 2020-03-15 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0009_ingredientalternative_ingredientalternativegrouprelation_ingredientgroup_recipeingredientalternative'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeRecipeSetRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving', models.PositiveIntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.RecipeLabel')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.RecipeSet')),
            ],
        ),
    ]
