# Generated by Django 2.1.4 on 2018-12-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0010_auto_20180317_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.FoodCategory'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Food'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='inlist',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipebook.MeasureUnit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipebook.StepSequence'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.RecipeCategory'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.StepSequence'),
        ),
        migrations.AlterField(
            model_name='step',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.StepSequence'),
        ),
    ]
