# Generated by Django 3.0.2 on 2020-03-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0010_recipelabel_reciperecipesetrelation_recipeset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='tools',
        ),
    ]
