# Generated by Django 3.0.2 on 2020-03-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0012_auto_20200315_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['sequence', 'pos']},
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('sequence', 'pos')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='step',
            order_with_respect_to=None,
        ),
    ]
