# Generated by Django 2.1.4 on 2019-07-24 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0012_auto_20190723_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionToolRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Step')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientToolRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Recipe')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Step')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipebook.Tool')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='stepsequence',
            order_with_respect_to='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='execution_tools',
            field=models.ManyToManyField(blank=True, related_name='recipe_execution_set', through='recipebook.ExecutionToolRelation', to='recipebook.Tool'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_tools',
            field=models.ManyToManyField(blank=True, related_name='recipe_ingredient_set', through='recipebook.IngredientToolRelation', to='recipebook.Tool'),
        ),
    ]
