# Generated by Django 2.1.4 on 2019-07-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0013_auto_20190724_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepsequence',
            name='parent',
        ),
    ]
