# Generated by Django 2.1.4 on 2019-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0014_remove_stepsequence_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontoolrelation',
            name='reuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredienttoolrelation',
            name='reuse',
            field=models.BooleanField(default=False),
        ),
    ]
