# Generated by Django 2.1.4 on 2019-07-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0015_auto_20190724_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executiontoolrelation',
            old_name='reuse',
            new_name='use_new',
        ),
        migrations.RenameField(
            model_name='ingredienttoolrelation',
            old_name='reuse',
            new_name='use_new',
        ),
    ]
