# Generated by Django 3.0.2 on 2020-03-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0017_ingredientingredientgrouprelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['food', 'quantity', 'measure', 'preparation']},
        ),
    ]
