# Generated by Django 3.0.2 on 2020-03-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0018_auto_20200320_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientgroup',
            name='ingredients',
        ),
    ]
