# Generated by Django 3.0.2 on 2020-03-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0019_remove_ingredientgroup_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientalternative',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='recipelabel',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='recipeset',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='stepsequence',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
