# Generated by Django 3.0.2 on 2020-03-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0020_auto_20200320_0653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measureunit',
            unique_together={('name', 'apply_to')},
        ),
    ]
