# -*- coding: utf-8 -*-
from django.conf import settings
from django.utils.translation import ugettext as _


#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=51B0I0kbRt14+E48dwffUpTkImm


# *** Primary color:

#    shade 0 = #E7DE92 = rgb(231,222,146) = rgba(231,222,146,1)
#    shade 1 = #FFFBD7 = rgb(255,251,215) = rgba(255,251,215,1)
#    shade 2 = #FFF8BE = rgb(255,248,190) = rgba(255,248,190,1)
#    shade 3 = #CEC368 = rgb(206,195,104) = rgba(206,195,104,1)
#    shade 4 = #B2A63F = rgb(178,166, 63) = rgba(178,166, 63,1)

# *** Secondary color (1):

#    shade 0 = #C1D989 = rgb(193,217,137) = rgba(193,217,137,1)
#    shade 1 = #E9F4CE = rgb(233,244,206) = rgba(233,244,206,1)
#    shade 2 = #DDF0B2 = rgb(221,240,178) = rgba(221,240,178,1)
#    shade 3 = #A5C262 = rgb(165,194, 98) = rgba(165,194, 98,1)
#    shade 4 = #87A73B = rgb(135,167, 59) = rgba(135,167, 59,1)

# *** Secondary color (2):

#    shade 0 = #E7C992 = rgb(231,201,146) = rgba(231,201,146,1)
#    shade 1 = #FFF1D7 = rgb(255,241,215) = rgba(255,241,215,1)
#    shade 2 = #FFE8BE = rgb(255,232,190) = rgba(255,232,190,1)
#    shade 3 = #CEAA68 = rgb(206,170,104) = rgba(206,170,104,1)
#    shade 4 = #B28A3F = rgb(178,138, 63) = rgba(178,138, 63,1)


#####  Generated by Paletton.com (c) 2002-2014

#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=51B0I0kw0w0jyC+oRxVy4oIDfjr

# forti

# *** Primary color:

#    shade 0 = #FFE400 = rgb(255,228,  0) = rgba(255,228,  0,1)
#    shade 1 = #FFEE63 = rgb(255,238, 99) = rgba(255,238, 99,1)
#    shade 2 = #FFEA39 = rgb(255,234, 57) = rgba(255,234, 57,1)
#    shade 3 = #C5B000 = rgb(197,176,  0) = rgba(197,176,  0,1)
#    shade 4 = #9B8A00 = rgb(155,138,  0) = rgba(155,138,  0,1)

# *** Secondary color (1):

#    shade 0 = #A8F000 = rgb(168,240,  0) = rgba(168,240,  0,1)
#    shade 1 = #C7F45F = rgb(199,244, 95) = rgba(199,244, 95,1)
#    shade 2 = #B9F136 = rgb(185,241, 54) = rgba(185,241, 54,1)
#    shade 3 = #82B900 = rgb(130,185,  0) = rgba(130,185,  0,1)
#    shade 4 = #669100 = rgb(102,145,  0) = rgba(102,145,  0,1)

# *** Secondary color (2):

#    shade 0 = #FFA500 = rgb(255,165,  0) = rgba(255,165,  0,1)
#    shade 1 = #FFC863 = rgb(255,200, 99) = rgba(255,200, 99,1)
#    shade 2 = #FFB939 = rgb(255,185, 57) = rgba(255,185, 57,1)
#    shade 3 = #C58000 = rgb(197,128,  0) = rgba(197,128,  0,1)
#    shade 4 = #9B6400 = rgb(155,100,  0) = rgba(155,100,  0,1)


# #####  Generated by Paletton.com (c) 2002-2014


class MenuRow(object):
    def __init__(self,txt,xurl):
        self.txt=txt
        self.url=xurl

class HomeRow(object):
    def __init__(self,txt,xurl,img):
        self.txt=txt
        self.url=xurl
        self.img=settings.STATIC_URL+"bigicons/"+img

class HomeTitle(object):
    def __init__(self,txt,img):
        self.txt=txt
        self.img=settings.STATIC_URL+"bigicons/"+img

def get_template_vars(request=None):
    T={
        "BACKGROUND":settings.STATIC_URL+"backgrounds/biblioteca.png",
        "JQUERY":settings.STATIC_URL+"js/jquery-1.11.0.js",
        "JQUERY_UI":settings.STATIC_URL+"js/jquery-ui-1.11.0.custom.js",
        "JQUERY_CANVAS":settings.STATIC_URL+"js/jcanvas-14.08.16.min.js",
        "JQUERY_UI_SANTACLARA_WIDGETS":settings.STATIC_URL+"santaclara_base/jquery-ui-santaclara-widgets.js",
        "JQUERY_UI_SANTACLARA_CSS":settings.STATIC_URL+"santaclara_base/jquery-ui-santaclara-widgets.css",
        "JQUERY_UI_CSS":settings.STATIC_URL+"css/jquery-ui-1.11.0.bookcolor.css",
        "BRAND": settings.STATIC_URL+"images/brand",
        "STATIC_IMG": settings.STATIC_URL+"images/img",
        "FONTS": settings.STATIC_URL+"fonts",
        }

    T["HEADER_MENU"]=[ ( MenuRow(_("Home"),"/"), [] ),
                       ( MenuRow(_("Catalog"),"/bibliography/catalog/"), [] ),
                       ( MenuRow(_("Categories"),"/bibliography/categories/"), [] ),
                       ( MenuRow(_("Lists"),"/bibliography/"), [] ),
                       ( MenuRow(_("Tools"),""), 
                         [ 
                             MenuRow(_("Insert"),"/bibliography/insert/"),
                             MenuRow(_("Create publisher"),"/bibliography/publisher/create/"),
                             MenuRow(_("Create author"),"/bibliography/author/create/"),
                             MenuRow(_("Create book"),"/bibliography/book/create/"),
                             MenuRow(_("Categorizer: category to category"),"/bibliography/categories/categorizer/"),
                             MenuRow(_("Categorizer: book to category"),"/bibliography/books/categorizer/"),
                         ] ),
                       ]

    home_sections=[ ( HomeTitle("Bacheca","default_section.png"),
                      ( HomeRow("Avvisi","","default_section.png"),
                        HomeRow(_("Introductions"),"/profiles/introductions/", "default_section.png"),
                        HomeRow(_("FAQs"), "/help/faqs/", "default_section.png"),
                        HomeRow(_("Rules"), "/help/rules/", "default_section.png") )),
                    ( HomeTitle("Pubblicità", "default_section.png"),
                      ( HomeRow(_("Books"), "/books/", "default_section.png"),
                        HomeRow("Recensioni", "", "default_section.png"),
                        HomeRow(_("Events"), "","default_section.png"),
                        HomeRow("Concorsi","", "default_section.png") )),
                    ( HomeTitle(_("User's Area"), "default_section.png"),
                      ( HomeRow(_("Users"), "/profiles/users/" ,"default_section.png"),
                        HomeRow(_("Manual"), "/help/manual/", "default_section.png") ,
                        HomeRow(_("Help"), "/forum/help/", "default_section.png") ,
                        HomeRow("Segreteria", "" , "default_section.png"),
                        HomeRow("Area discussioni", "/forum/" , "default_section.png") )),
                    ( HomeTitle(_("Creativity"), "default_section.png"),
                      ( HomeRow(_("Texts"),"/documents/documenttexts/", "default_section.png"),
                        HomeRow(_("Novels"),"", "default_section.png"),
                        HomeRow(_("Poetry"),"", "default_section.png"),
                        HomeRow(_("Theater"), "","default_section.png"),
                        HomeRow("Sceneggiature","", "default_section.png"),
                        HomeRow("Disegni", "","default_section.png") )),
                    ( HomeTitle(_("World Building"), "default_section.png"),
                      ( HomeRow("Cultura materiale", "","default_section.png"),
                        HomeRow("Lingue artificiali", "","default_section.png"),
                        HomeRow(_("Cartography"), "","default_section.png"),
                        HomeRow(_("Documentation"), "","default_section.png") )),
                    ]
    
    T["HOME_SECTIONS"]=home_sections

    return(T)
