# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 16:03
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

def load_bibliography(apps, schema_editor):
    PublisherIsbn=apps.get_model("bibliography","PublisherIsbn")
    Publisher=apps.get_model("bibliography","Publisher")
    publisher,created=Publisher.objects.get_or_create(id=0,defaults={"name":"-","full_name":"No Publisher"})
    isbn,created=PublisherIsbn.objects.get_or_create(isbn="SENZA",defaults={"preferred":publisher})
    publisher.isbns.add(isbn)
    publisher.save()
    
    call_command("loaddata", "author_roles")
    call_command("loaddata", "volume_types")
    call_command("loaddata", "name_types")
    call_command("loaddata", "name_formats")
    call_command("loaddata", "name_format_collections")

    NameFormatCollection=apps.get_model("bibliography","NameFormatCollection")
    Author=apps.get_model("bibliography","Author")
    PersonCache=apps.get_model("bibliography","PersonCache")
    aavv_fc,created=NameFormatCollection.objects.get_or_create(label="aavv")
    p_cache,created=PersonCache.objects.get_or_create(
        long_name = unicode(aavv_fc.long_format.pattern),
        short_name = unicode(aavv_fc.short_format.pattern),
        list_name = unicode(aavv_fc.list_format.pattern),
        ordering_name = unicode(aavv_fc.ordering_format.pattern)
    )
    # p_cache=PersonCache()
    
    # p_cache.long_name = unicode(aavv_fc.long_format.pattern)
    # p_cache.short_name = unicode(aavv_fc.short_format.pattern)
    # p_cache.list_name = unicode(aavv_fc.list_format.pattern)
    # p_cache.ordering_name = unicode(aavv_fc.ordering_format.pattern)
    # p_cache.save()

    aav,created=Author.objects.get_or_create(format_collection=aavv_fc,cache=p_cache)

    # aavv=Author(format_collection=aavv_fc,cache=p_cache)
    # aavv.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_bibliography),
    ]
