# Generated by Django 3.0.2 on 2020-02-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorrelation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='authorrelation',
            name='year_label',
        ),
        migrations.AddField(
            model_name='article',
            name='html_cache',
            field=models.TextField(blank=True, default='', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='html_cache',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='html_cache',
            field=models.TextField(blank=True, default='', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='personcache',
            name='lower_initial',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='personcache',
            name='upper_initial',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='personnamerelation',
            name='case_rule',
            field=models.CharField(choices=[('latin', 'latin'), ('turkic', 'turkic')], default='latin', max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_book',
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_ced',
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='migrauthor',
            name='cod',
            field=models.CharField(db_index=True, default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='migrauthor',
            name='ind',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='label',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
