# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0002_auto_20170111_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='page_begin',
            field=models.CharField(blank=True, default='x', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='page_end',
            field=models.CharField(blank=True, default='x', max_length=10),
        ),
        migrations.AlterField(
            model_name='authorrole',
            name='action',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_cache10',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_cache13',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_crc10',
            field=models.CharField(default='Y', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_crc13',
            field=models.CharField(default='Y', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='bookseriewithoutisbn',
            name='title_prefix',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='migrauthor',
            name='cod',
            field=models.CharField(db_index=True, default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='personcache',
            name='list_name',
            field=models.CharField(default='-', max_length=4096),
        ),
        migrations.AlterField(
            model_name='personcache',
            name='long_name',
            field=models.CharField(default='-', max_length=4096),
        ),
        migrations.AlterField(
            model_name='personcache',
            name='ordering_name',
            field=models.CharField(default='-', max_length=4096),
        ),
        migrations.AlterField(
            model_name='personcache',
            name='short_name',
            field=models.CharField(default='-', max_length=4096),
        ),
        migrations.AlterField(
            model_name='personnamerelation',
            name='value',
            field=models.CharField(default='-', max_length=4096),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_format',
            field=models.CharField(default='%Y-%m-%d', max_length=4096),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issn_crc',
            field=models.CharField(default='Y', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='url',
            field=models.CharField(default='--', max_length=4096),
        ),
        migrations.AlterField(
            model_name='repositorycachebook',
            name='city',
            field=models.CharField(default=' ', max_length=4096),
        ),
        migrations.AlterField(
            model_name='repositorycachebook',
            name='publisher',
            field=models.CharField(default=' ', max_length=4096),
        ),
        migrations.AlterField(
            model_name='repositorycachebook',
            name='title',
            field=models.CharField(default=' ', max_length=4096),
        ),
        migrations.AlterField(
            model_name='repositorycachebook',
            name='year',
            field=models.CharField(blank=True, default=' ', max_length=4096),
        ),
        migrations.AlterField(
            model_name='volumetype',
            name='read_as',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
