# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0005_book_year_ipotetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_ipotetic',
            field=models.BooleanField(default=False),
        ),
    ]
