# Generated by Django 2.1.4 on 2018-12-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0006_issue_date_ipotetic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateplacename',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Place'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Issue'),
        ),
        migrations.AlterField(
            model_name='articleauthorrelation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Article'),
        ),
        migrations.AlterField(
            model_name='authorrelation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Author'),
        ),
        migrations.AlterField(
            model_name='authorrelation',
            name='author_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.AuthorRole'),
        ),
        migrations.AlterField(
            model_name='authorrelation',
            name='content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Publisher'),
        ),
        migrations.AlterField(
            model_name='bookauthorrelation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Book'),
        ),
        migrations.AlterField(
            model_name='bookseriewithoutisbn',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Publisher'),
        ),
        migrations.AlterField(
            model_name='categorylanguagerelation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Category'),
        ),
        migrations.AlterField(
            model_name='categorylanguagerelation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.LanguageVariety'),
        ),
        migrations.AlterField(
            model_name='categorypersonrelation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Category'),
        ),
        migrations.AlterField(
            model_name='categorypersonrelation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Person'),
        ),
        migrations.AlterField(
            model_name='categoryplacerelation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Category'),
        ),
        migrations.AlterField(
            model_name='categoryplacerelation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Place'),
        ),
        migrations.AlterField(
            model_name='categoryrelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_set', to='bibliography.Category'),
        ),
        migrations.AlterField(
            model_name='categoryrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_set', to='bibliography.Category'),
        ),
        migrations.AlterField(
            model_name='categorytimespanrelation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Category'),
        ),
        migrations.AlterField(
            model_name='categorytimespanrelation',
            name='time_span',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.TimeSpan'),
        ),
        migrations.AlterField(
            model_name='categorytreenode',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.IssueType'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Volume'),
        ),
        migrations.AlterField(
            model_name='issueauthorrelation',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Issue'),
        ),
        migrations.AlterField(
            model_name='languagefamilyfamilyrelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_set', to='bibliography.LanguageFamily'),
        ),
        migrations.AlterField(
            model_name='languagefamilyfamilyrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_set', to='bibliography.LanguageFamily'),
        ),
        migrations.AlterField(
            model_name='languagefamilyrelation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.LanguageFamily'),
        ),
        migrations.AlterField(
            model_name='languagefamilyrelation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Language'),
        ),
        migrations.AlterField(
            model_name='languagevariety',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Language'),
        ),
        migrations.AlterField(
            model_name='languagevariety',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bibliography.LanguageVarietyType'),
        ),
        migrations.AlterField(
            model_name='migrauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Author'),
        ),
        migrations.AlterField(
            model_name='migrpublisherriviste',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Publisher'),
        ),
        migrations.AlterField(
            model_name='nameformatcollection',
            name='list_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_format_set', to='bibliography.NameFormat'),
        ),
        migrations.AlterField(
            model_name='nameformatcollection',
            name='long_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='long_format_set', to='bibliography.NameFormat'),
        ),
        migrations.AlterField(
            model_name='nameformatcollection',
            name='ordering_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordering_format_set', to='bibliography.NameFormat'),
        ),
        migrations.AlterField(
            model_name='nameformatcollection',
            name='short_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_format_set', to='bibliography.NameFormat'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cache',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='bibliography.PersonCache'),
        ),
        migrations.AlterField(
            model_name='person',
            name='format_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.NameFormatCollection'),
        ),
        migrations.AlterField(
            model_name='personnamerelation',
            name='name_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.NameType'),
        ),
        migrations.AlterField(
            model_name='personnamerelation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Person'),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.PlaceType'),
        ),
        migrations.AlterField(
            model_name='placerelation',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_set', to='bibliography.Place'),
        ),
        migrations.AlterField(
            model_name='placerelation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_set', to='bibliography.Place'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Publisher'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.VolumeType'),
        ),
        migrations.AlterField(
            model_name='publisheraddress',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.PublisherState'),
        ),
        migrations.AlterField(
            model_name='publisheraddresspublisherrelation',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.PublisherAddress'),
        ),
        migrations.AlterField(
            model_name='publisheraddresspublisherrelation',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisherisbn',
            name='preferred',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, to='bibliography.Publisher'),
        ),
        migrations.AlterField(
            model_name='repositorycacheauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.RepositoryCacheBook'),
        ),
        migrations.AlterField(
            model_name='timepoint',
            name='modifier',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='bibliography.DateModifier'),
        ),
        migrations.AlterField(
            model_name='timespan',
            name='begin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='begin_set', to='bibliography.TimePoint'),
        ),
        migrations.AlterField(
            model_name='timespan',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_set', to='bibliography.TimePoint'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliography.Publication'),
        ),
    ]
