# Generated by Django 2.2.5 on 2019-09-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskervilleauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
