# Generated by Django 2.2.5 on 2019-09-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskervilleauth', '0003_auto_20190919_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(default=160, verbose_name='height (cm)'),
        ),
        migrations.AddField(
            model_name='user',
            name='lifestyle',
            field=models.CharField(choices=[('sedentary', 'sedentary'), ('active', 'active'), ('very active', 'very active')], default='sedentary', max_length=128),
            preserve_default=False,
        ),
    ]
