# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 13:13


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('number', models.CharField(max_length=1024)),
                ('identifier', models.CharField(editable=False, max_length=4096, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Argument')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='ArgumentClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ArgumentSelector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=4096, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArgumentSuffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('number', models.CharField(max_length=1024)),
                ('identifier', models.CharField(editable=False, max_length=4096)),
            ],
            options={
                'ordering': ['collection', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='ArgumentSuffixCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=4096)),
                ('description', models.CharField(max_length=4096)),
                ('phase', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_classification', models.CharField(max_length=1024)),
                ('copies_number', models.PositiveIntegerField(default=1)),
                ('short_identifier', models.CharField(editable=False, max_length=4096)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.ArgumentClassification')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='FormClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LanguageAuxiliaryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LanguageClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliaries', models.ManyToManyField(blank=True, to='classification.LanguageAuxiliaryNumber')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PlaceAuxiliaryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PlaceClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliaries', models.ManyToManyField(blank=True, to='classification.PlaceAuxiliaryNumber')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ShortClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1024, unique=True)),
                ('priority', models.PositiveIntegerField()),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.ArgumentClassification')),
                ('forms', models.ManyToManyField(blank=True, to='classification.FormClassification')),
                ('languages', models.ManyToManyField(blank=True, to='classification.LanguageClassification')),
                ('places', models.ManyToManyField(blank=True, to='classification.PlaceClassification')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TimeClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='shortclassification',
            name='times',
            field=models.ManyToManyField(blank=True, to='classification.TimeClassification'),
        ),
        migrations.AddField(
            model_name='placeclassification',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.PlaceNumber'),
        ),
        migrations.AddField(
            model_name='languageclassification',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.LanguageNumber'),
        ),
        migrations.AddField(
            model_name='classification',
            name='forms',
            field=models.ManyToManyField(blank=True, to='classification.FormClassification'),
        ),
        migrations.AddField(
            model_name='classification',
            name='languages',
            field=models.ManyToManyField(blank=True, to='classification.LanguageClassification'),
        ),
        migrations.AddField(
            model_name='classification',
            name='places',
            field=models.ManyToManyField(blank=True, to='classification.PlaceClassification'),
        ),
        migrations.AddField(
            model_name='classification',
            name='short',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='classification.ShortClassification'),
        ),
        migrations.AddField(
            model_name='classification',
            name='times',
            field=models.ManyToManyField(blank=True, to='classification.TimeClassification'),
        ),
        migrations.AddField(
            model_name='argumentsuffix',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.ArgumentSuffixCollection'),
        ),
        migrations.AddField(
            model_name='argumentsuffix',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.ArgumentSuffix'),
        ),
        migrations.AddField(
            model_name='argumentselector',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.ArgumentSuffixCollection'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together=set([('argument', 'object_classification'), ('content_type', 'object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='argumentsuffix',
            unique_together=set([('collection', 'identifier')]),
        ),
    ]
