# Generated by Django 3.0.2 on 2020-02-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ArgumentSuffixCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=4096)),
                ('description', models.CharField(max_length=4096)),
                ('phase', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LanguageAuxiliaryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LanguageClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliaries', models.ManyToManyField(blank=True, to='classification.LanguageAuxiliaryNumber')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PlaceAuxiliaryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PlaceClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliaries', models.ManyToManyField(blank=True, to='classification.PlaceAuxiliaryNumber')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TimeClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=4096)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ShortClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1024, unique=True)),
                ('priority', models.PositiveIntegerField()),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentClassification')),
                ('forms', models.ManyToManyField(blank=True, to='classification.FormClassification')),
                ('languages', models.ManyToManyField(blank=True, to='classification.LanguageClassification')),
                ('places', models.ManyToManyField(blank=True, to='classification.PlaceClassification')),
                ('times', models.ManyToManyField(blank=True, to='classification.TimeClassification')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='placeclassification',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.PlaceNumber'),
        ),
        migrations.AddField(
            model_name='languageclassification',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.LanguageNumber'),
        ),
        migrations.CreateModel(
            name='ArgumentSelector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=4096, unique=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentSuffixCollection')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('number', models.CharField(max_length=1024)),
                ('identifier', models.CharField(editable=False, max_length=4096, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.Argument')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_classification', models.CharField(max_length=1024)),
                ('copies_number', models.PositiveIntegerField(default=1)),
                ('short_identifier', models.CharField(editable=False, max_length=4096)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentClassification')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('forms', models.ManyToManyField(blank=True, to='classification.FormClassification')),
                ('languages', models.ManyToManyField(blank=True, to='classification.LanguageClassification')),
                ('places', models.ManyToManyField(blank=True, to='classification.PlaceClassification')),
                ('short', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='classification.ShortClassification')),
                ('times', models.ManyToManyField(blank=True, to='classification.TimeClassification')),
            ],
            options={
                'unique_together': {('content_type', 'object_id'), ('argument', 'object_classification')},
            },
        ),
        migrations.CreateModel(
            name='ArgumentSuffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('number', models.CharField(max_length=1024)),
                ('identifier', models.CharField(editable=False, max_length=4096)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentSuffixCollection')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentSuffix')),
            ],
            options={
                'ordering': ['collection', 'identifier'],
                'unique_together': {('collection', 'identifier')},
            },
        ),
    ]
