# Generated by Django 2.1.4 on 2018-12-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.Argument'),
        ),
        migrations.AlterField(
            model_name='argumentselector',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentSuffixCollection'),
        ),
        migrations.AlterField(
            model_name='argumentsuffix',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentSuffixCollection'),
        ),
        migrations.AlterField(
            model_name='argumentsuffix',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentSuffix'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentClassification'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='short',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='classification.ShortClassification'),
        ),
        migrations.AlterField(
            model_name='languageclassification',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.LanguageNumber'),
        ),
        migrations.AlterField(
            model_name='placeclassification',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.PlaceNumber'),
        ),
        migrations.AlterField(
            model_name='shortclassification',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classification.ArgumentClassification'),
        ),
    ]
