# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 15:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0034_auto_20170105_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAuthorRelation',
            fields=[
                ('authorrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliography.AuthorRelation')),
                ('pos', models.PositiveIntegerField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Issue')),
            ],
            options={
                'ordering': ['pos'],
            },
            bases=('bibliography.authorrelation', models.Model),
        ),
        migrations.RemoveField(
            model_name='comic',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='issue_ptr',
        ),
        migrations.RemoveField(
            model_name='comicauthorrelation',
            name='authorrelation_ptr',
        ),
        migrations.RemoveField(
            model_name='comicauthorrelation',
            name='comic',
        ),
        migrations.DeleteModel(
            name='Comic',
        ),
        migrations.DeleteModel(
            name='ComicAuthorRelation',
        ),
        migrations.AddField(
            model_name='issue',
            name='authors',
            field=models.ManyToManyField(blank=True, through='bibliography.IssueAuthorRelation', to='bibliography.Author'),
        ),
    ]
