# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0004_auto_20170715_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_ipotetic',
            field=models.BooleanField(default=False),
        ),
    ]
