# Generated by Django 2.2.5 on 2019-09-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0007_auto_20181222_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='html_cache',
            field=models.TextField(blank=True, default='', editable=False, null=True),
        ),
    ]
