# Generated by Django 2.2.5 on 2019-09-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0008_issue_html_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='html_cache',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
