# Generated by Django 2.2.5 on 2019-09-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0009_book_html_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_cache',
            field=models.TextField(blank=True, default='', editable=False, null=True),
        ),
    ]
