# Generated by Django 2.2.5 on 2019-09-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0010_article_html_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnamerelation',
            name='case_rule',
            field=models.CharField(choices=[('latin', 'latin'), ('turkic', 'turkic')], default='latin', max_length=128),
        ),
    ]
