# Generated by Django 2.2.5 on 2019-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0011_personnamerelation_case_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcache',
            name='lower_initial',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='personcache',
            name='upper_initial',
            field=models.CharField(default='-', max_length=4),
        ),
    ]
