# Generated by Django 3.0 on 2020-12-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectcontainerrelation',
            unique_together={('content_type', 'object_id')},
        ),
    ]
