# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0004_auto_20180317_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='inlist',
            field=models.BooleanField(default=True),
        ),
    ]
