# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0006_auto_20180317_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipebook.RecipeCategory'),
            preserve_default=False,
        ),
    ]
