# Generated by Django 2.1.4 on 2019-07-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0011_auto_20181222_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureunit',
            name='plural',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='base',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('qb', 'qb')], default='g', max_length=128),
        ),
    ]
