# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.FilePathField(max_length=1024, path='/home/chiara/foto/full', recursive=True)),
                ('thumb_path', models.FilePathField(max_length=1024, path='/home/chiara/foto/thumb', recursive=True)),
                ('description', models.CharField(blank=True, max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMetaDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.MetaLabel')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Photo')),
            ],
        ),
    ]
