# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20170516_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='type',
            new_name='mimetype',
        ),
    ]
