# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20170516_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExifDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='ExifLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exif_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='photometadatum',
            name='value',
            field=models.CharField(max_length=8192),
        ),
        migrations.AddField(
            model_name='exifdatum',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.ExifLabel'),
        ),
        migrations.AddField(
            model_name='exifdatum',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Photo'),
        ),
    ]
