# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20170516_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='exiflabel',
            name='type',
            field=models.CharField(choices=[('tag', 'tag'), ('gps', 'gps')], default='tag', max_length=128),
            preserve_default=False,
        ),
    ]
