# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20170516_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exiflabel',
            name='exif_id',
        ),
        migrations.AlterField(
            model_name='exiflabel',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
