# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20170516_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='exiflabel',
            name='category',
            field=models.CharField(default='Image', max_length=128),
            preserve_default=False,
        ),
    ]
