# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_exiflabel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExifType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('exif_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exiflabel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.ExifType'),
        ),
    ]
