# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_photo_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='orientation',
        ),
        migrations.AddField(
            model_name='photo',
            name='mirrored',
            field=models.CharField(choices=[('no', 'no'), ('horizontal', 'horizontal'), ('vertical', 'vertical')], default='no', max_length=128),
        ),
        migrations.AddField(
            model_name='photo',
            name='rotated',
            field=models.CharField(choices=[('no', 'no'), ('90 ccw', '90 ccw'), ('90 cw', '90 cw'), ('180', '180')], default='no', max_length=128),
        ),
    ]
