# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_auto_20170516_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['datetime']},
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, to='archive.Photo'),
        ),
    ]
