# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_auto_20170517_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name']},
        ),
    ]
