# Generated by Django 2.1.4 on 2018-12-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_auto_20170517_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifdatum',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.ExifLabel'),
        ),
        migrations.AlterField(
            model_name='exifdatum',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Photo'),
        ),
        migrations.AlterField(
            model_name='exiflabel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.ExifType'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.ImageFormat'),
        ),
        migrations.AlterField(
            model_name='photometadatum',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.MetaLabel'),
        ),
        migrations.AlterField(
            model_name='photometadatum',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Photo'),
        ),
    ]
